spring:
  config:
    import: classpath:/console.yaml,optional:file:${georchestra.datadir}/default.properties,optional:file:${georchestra.datadir}/console/console.yaml,optional:file:${georchestra.datadir}/console/console.properties
  application:
    name: console
  messages:
    basename: application
    fallback-to-system-locale: false
  thymeleaf:
    cache: false #Only for development, to be able to see changes in templates without restarting the application
  datasource:
    url: jdbc:postgresql://${pgsqlHost}:${pgsqlPort}/${pgsqlDatabase}?currentSchema=console
    username: ${pgsqlUser}
    password: ${pgsqlPassword}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  ldap:
    urls: ${ldapScheme}://${ldapHost}:${ldapPort}
    base: ${ldapBaseDn}
    username: ${ldapAdminDn}
    password: ${ldapAdminPassword}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  servlet:
    context-path: /console
  tomcat:
    max-multipart-files: 100
