submit.label=Submit
form.error=The form contains errors
emailWasSent.title=E-mail sent
emailWasSent.link=Home
emailWasSentForEmailChange.body=A validation link has been sent to your new e-mail address. Please, check your e-mail box.
changeEmailForm.title=Change e-mail address.
changeEmailForm.description=You will receive a validation link to your new e-mail address to confirm this change.
changeEmailForm.fieldset.email=New e-mail address
changePasswordForm.title=Change password.
changePasswordForm.description=Update your password for this account.
changePasswordForm.fieldset.password=Password
changePasswordForm.success=Password updated successfully
editOrgDetailsForm.title=Organization details.
editOrgDetailsForm.description=Update your organization information.
editOrgDetailsForm.fieldset.orgDetails=Organization details
editOrgDetailsForm.success=Organization updated successfully

editUserDetailsForm.title=User details.
editUserDetailsForm.description=In this page you can manage your account informations and modify your password.
editUserDetailsForm.fieldset.userDetails=User details
editUserDetailsForm.fieldset.credentials=Credentials
editUserDetailsForm.changePassword.link=Change Password
editUserDetailsForm.changeEmail.link=Change e-mail
editUserDetailsForm.success=User details updated successfully
editUserDetailsForm.organisation=Organization
editUserDetailsForm.url=Website
editUserDetailsForm.members=Members
editUserDetailsForm.editOrg=Edit Organization
editUserDetailsForm.gdpr=GDPR
editUserDetailsForm.download=Download my data
editUserDetailsForm.delete=Delete my account
editUserDetailsForm.downloadMsg=In accordance with the European General Data Protection Regulation, you are able to download your data on this platform at any time.
editUserDetailsForm.deleteMsg=You may also permanently delete your account. WARNING: this cannot be undone !
editUserDetailsForm.deleteConfirm=Do you really want to delete your account? This action is irreversible.
editUserDetailsForm.deleteFail=Unable to delete your account.

description.label=Description
description.placeholder=Description
name.label=Name
address.label=Address
email.label=E-mail
email.placeholder=E-mail
facsimile.label=Fax
facsimile.placeholder=Fax
facsimile.error.invalidFormat=Fax number can only contain digits, spaces, and + ( ) . -
firstName.label=First Name
firstName.placeholder=First Name
org.label=Organization
org.empty=empty
url.label=Website
mail.label=E-mail
logo.label=Logo
orgUniqueId.label=Organization ID
password.label=Password
password.label.empty=Empty
password.label.veryweak=Very weak
password.label.weak=Weak
password.label.good=Good
password.label.strong=Strong
password.placeholder=Password
password.policy=Password policy
password.policy.size=Minimum length: {0} characters
password.error.sizeError=The password must have at least {0} characters
password.error.required=Password is required
password.error.requireLowers=The password must contain lower cases
password.error.requireUppers=The password must contain upper cases
password.error.requireDigits=The password must contain digits
password.error.requireSpecials=The password must contain special characters
phone.label=Phone
phone.placeholder=Phone
phone.error.invalidFormat=Phone number can only contain digits, spaces, and + ( ) . -
postalAddress.label=Postal address
postalAddress.placeholder=Postal address
surname.label=Surname
surname.placeholder=Surname
title.label=Job title
title.placeholder=Job title
uid.label=User ID
confirmPassword.label=Confirm password
confirmPassword.placeholder=Confirm password
confirmPassword.error.pwdNotEquals=Passwords do not match
