pgsqlHost=database
pgsqlPort=5432
pgsqlDatabase=georchestra
pgsqlUser=georchestra
pgsqlPassword=georchestra
ldapHost=ldap
ldapPort=389
ldapScheme=ldap
ldapBaseDn=dc=georchestra,dc=org
ldapAdminDn=cn=admin,dc=georchestra,dc=org
ldapAdminPassword=secret
ldapUsersRdn=ou=users
ldapRolesRdn=ou=roles
ldapOrgsRdn=ou=orgs
smtpPort=25
headerScript=http://localhost:8090/_header.js
headerHeight=90
useLegacyHeader=false
headerUrl=/header/
georchestraStylesheet=http://localhost:8090/stylesheet.css
headerConfigFile=http://localhost:8090/header_config.json
logoUrl=https://www.georchestra.org/public/georchestra-logo.svg
analyticsEnabled=false
enableRabbitmqEvents=false
rabbitmqHost=rabbitmq
rabbitmqUser=georchestra
rabbitmqPassword=georchestra
rabbitmqPort=5672
domainName=localhost:8080
instanceName=geOrchestra
smtpHost=smtp
