pgsqlHost=localhost
pgsqlPort=15432
pgsqlDatabase=georchestra
pgsqlUser=georchestra
pgsqlPassword=georchestra

# Only to teste connectivity to geonetwork database, used for GPRD download
# pgsqlGNHost=database
# pgsqlGNPort=5432
# pgsqlGNDatabase=georchestra
# pgsqlGNUser=georchestra
# pgsqlGNPassword=georchestra

ldapScheme: ldap
ldapHost: localhost
ldapPort: 3389
ldapBaseDn=dc=georchestra,dc=org
ldapAdminDn=cn=admin,dc=georchestra,dc=org
ldapAdminPassword=secret
ldapUsersRdn=ou=users
ldapRolesRdn=ou=roles
ldapOrgsRdn=ou=orgs
smtpPort=1025
headerScript=http://localhost:8090/_header.js
headerHeight=90
useLegacyHeader=false
headerUrl=/header/
georchestraStylesheet=http://localhost:8090/stylesheet.css
headerConfigFile=http://localhost:8090/header_config.json
logoUrl=https://www.georchestra.org/public/georchestra-logo.svg
analyticsEnabled=false
enableRabbitmqEvents=false
rabbitmqHost=rabbitmq
rabbitmqUser=georchestra
rabbitmqPassword=georchestra
rabbitmqPort=5672
domainName=localhost:8080
publicUrl=http://localhost:8080
instanceName=geOrchestra
smtpHost=localhost
administratorEmail: psc@georchestra.org