# Password content requirements
# default: 8 characters minimum, all requirements to false
password.minimumLength=9
password.requireLowers=true
password.requireUppers=true
password.requireDigits=true
password.requireSpecials=true

orgTypeValues=Association,Company,NGO,Individual,Other
AreaMapCenter=9.3707, 42.0753
AreaMapZoom=7
AreasUrl=cities.geojson
AreasKey=INSEE_COM
AreasValue=NOM_COM_M
AreasGroup=INSEE_DEP


